// apps/mobile/src/components/bitnames/BitMessagesPreview.tsx
// apps/mobile/src/components/bitnames/BitMessagesPreview.tsx
//
// Ported 1:1 from apps/wallet/src/components/bitnames/BitMessagesPreview.vue.
//
// BitNames identity surface: the Coin News feed (via CoinNewsPreview) beside
// an identity card, the broadcast-news composer launcher, a contact list, and
// the selected BitNames thread.
//
// The Vue original used `v-model:selected-contact-name`; the RN port takes
// `selectedContactName` + `onSelectContact` to express the same two-way
// binding. `openFeedComposer` bumps a nonce that CoinNewsPreview watches to
// open its composer, exactly like the Vue `composerOpenNonce` ref.
//
// The Vue original lays the feed and aside out in two columns at `xl`; a
// phone is always narrower than `xl`, so the RN version stacks them.

import React, { useCallback, useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";

import { CoinNewsPreview } from "./CoinNewsPreview";
import { GRAY } from "../../theme/colors";

export interface BitNamesContact {
  name: string;
  displayName: string;
  useCase: string;
  status: string;
  lastSeen: string;
  paymentHint: string;
}

export interface BitNamesMessage {
  contact: string;
  side: "sent" | "received";
  time: string;
  body: string;
}

export interface BitMessagesPreviewProps {
  contacts: BitNamesContact[];
  messages: BitNamesMessage[];
  selectedContactName: string;
  onSelectContact: (contactName: string) => void;
}

export function BitMessagesPreview({
  contacts,
  messages,
  selectedContactName,
  onSelectContact,
}: BitMessagesPreviewProps): React.JSX.Element {
  const [composerOpenNonce, setComposerOpenNonce] = useState(0);

  const selectedContact = contacts.find(
    (contact) => contact.name === selectedContactName,
  );

  const selectedConversation = messages.filter(
    (message) => message.contact === selectedContactName,
  );

  const selectContact = useCallback(
    (contactName: string) => {
      onSelectContact(contactName);
    },
    [onSelectContact],
  );

  const openFeedComposer = useCallback(() => {
    setComposerOpenNonce((value) => value + 1);
  }, []);

  return (
    <View style={styles.root}>
      <View style={styles.hero}>
        <View style={styles.heroBody}>
          <View style={styles.heroEyebrowRow}>
            <Text style={styles.heroEyebrow}>BitNames identity</Text>
            <View style={styles.livePill}>
              <Text style={styles.livePillText}>Live Coin News</Text>
            </View>
          </View>

          <Text style={styles.heroTitle}>BitMessages</Text>
          <Text style={styles.heroSubtitle}>
            Broadcast signed posts, weekly news, and BitNames-linked messages
            across Signet from one wallet-native identity surface.
          </Text>
        </View>

        <View style={styles.statsRow}>
          <View style={styles.statCell}>
            <Text style={styles.statValueAmber}>—</Text>
            <Text style={styles.statLabel}>Messages</Text>
          </View>
          <View style={[styles.statCell, styles.statCellBordered]}>
            <Text style={styles.statValueEcash}>Live</Text>
            <Text style={styles.statLabel}>News</Text>
          </View>
          <View style={styles.statCell}>
            <Text style={styles.statValueEcash}>Signet</Text>
            <Text style={styles.statLabel}>Network</Text>
          </View>
        </View>
      </View>

      <View style={styles.feed}>
        <CoinNewsPreview
          showHero={false}
          composerOpenNonce={composerOpenNonce}
        />
      </View>

      <View style={styles.aside}>
        <View style={styles.section}>
          <View style={styles.identityHeader}>
            <View style={styles.identityHeaderText}>
              <Text style={styles.eyebrow}>Identity</Text>
              <Text style={styles.sectionTitle}>
                {selectedContact?.name ?? "No live identity selected"}
              </Text>
            </View>
            {selectedContact ? (
              <View style={styles.resolvedPill}>
                <Text style={styles.resolvedPillText}>Resolved</Text>
              </View>
            ) : null}
          </View>

          <View style={styles.detailList}>
            <View style={styles.detailRow}>
              <Text style={styles.detailKey}>Default feed</Text>
              <Text style={styles.detailValue}>Live indexed feed</Text>
            </View>
            <View style={styles.detailRow}>
              <Text style={styles.detailKey}>Message fee</Text>
              <Text style={styles.detailValueMono}>Indexed live</Text>
            </View>
            <View style={styles.detailRow}>
              <Text style={styles.detailKey}>Contact</Text>
              <Text style={styles.detailValueMono}>
                {selectedContact?.name ?? "—"}
              </Text>
            </View>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Broadcast News</Text>

          <View style={styles.infoBox}>
            <Text style={styles.infoBoxTitle}>Local composer available</Text>
            <Text style={styles.infoBoxBody}>
              Use the Coin News feed panel to build, sign, review, and broadcast
              a wallet-controlled OP_RETURN post.
            </Text>
          </View>

          <Pressable
            accessibilityRole="button"
            onPress={openFeedComposer}
            style={styles.primaryButton}
          >
            <Text style={styles.primaryButtonText}>Open Feed Composer</Text>
          </Pressable>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Contacts</Text>

          {contacts.length === 0 ? (
            <View style={styles.emptyBox}>
              <Text style={styles.emptyText}>
                No live BitNames contacts are indexed yet.
              </Text>
            </View>
          ) : (
            <View style={styles.contactList}>
              {contacts.map((contact) => (
                <Pressable
                  key={contact.name}
                  accessibilityRole="button"
                  onPress={() => selectContact(contact.name)}
                  style={[
                    styles.contactButton,
                    selectedContactName === contact.name
                      ? styles.contactButtonSelected
                      : null,
                  ]}
                >
                  <Text style={styles.contactName}>{contact.name}</Text>
                  <Text style={styles.contactUseCase}>{contact.useCase}</Text>
                </Pressable>
              ))}
            </View>
          )}
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>BitNames Thread</Text>
          <Text style={styles.threadHint}>
            {selectedContact?.paymentHint ??
              "No live BitNames conversation selected."}
          </Text>

          {selectedConversation.length === 0 ? (
            <View style={styles.emptyBox}>
              <Text style={styles.emptyText}>
                No live BitNames messages are indexed yet.
              </Text>
            </View>
          ) : (
            <View style={styles.threadList}>
              {selectedConversation.map((message) => (
                <View
                  key={`${message.contact}-${message.time}-${message.body}`}
                  style={styles.threadMessage}
                >
                  <Text style={styles.threadBody}>{message.body}</Text>
                  <Text style={styles.threadTime}>{message.time}</Text>
                </View>
              ))}
            </View>
          )}
        </View>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  root: {
    marginTop: 24,
    gap: 24,
  },
  hero: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: GRAY[800],
    backgroundColor: GRAY[950],
    padding: 24,
    gap: 20,
  },
  heroBody: {
    gap: 12,
  },
  heroEyebrowRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 8,
  },
  heroEyebrow: {
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 2,
    color: "#fb923c",
  },
  livePill: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(247,147,26,0.4)",
    backgroundColor: "rgba(67,20,7,0.6)",
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  livePillText: {
    fontSize: 12,
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: 1,
    color: "#fdba74",
  },
  heroTitle: {
    fontSize: 28,
    fontWeight: "900",
    color: "#ffffff",
  },
  heroSubtitle: {
    fontSize: 14,
    lineHeight: 22,
    color: GRAY[400],
  },
  statsRow: {
    flexDirection: "row",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: GRAY[800],
    backgroundColor: GRAY[950],
    padding: 12,
  },
  statCell: {
    flex: 1,
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  statCellBordered: {
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderColor: GRAY[800],
  },
  statValueAmber: {
    fontSize: 18,
    fontWeight: "900",
    color: "#fbbf24",
  },
  statValueEcash: {
    fontSize: 18,
    fontWeight: "900",
    color: "#fb923c",
  },
  statLabel: {
    fontSize: 10,
    textTransform: "uppercase",
    letterSpacing: 1,
    color: GRAY[500],
  },
  feed: {
    gap: 24,
  },
  aside: {
    gap: 24,
  },
  section: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: GRAY[800],
    backgroundColor: GRAY[950],
    padding: 20,
  },
  identityHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  identityHeaderText: {
    flex: 1,
  },
  eyebrow: {
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 2,
    color: GRAY[500],
  },
  sectionTitle: {
    marginTop: 8,
    fontSize: 20,
    fontWeight: "900",
    color: "#ffffff",
  },
  resolvedPill: {
    borderRadius: 999,
    backgroundColor: "#431407",
    paddingHorizontal: 12,
    paddingVertical: 4,
  },
  resolvedPillText: {
    fontSize: 12,
    fontWeight: "900",
    color: "#fdba74",
  },
  detailList: {
    marginTop: 20,
    gap: 12,
  },
  detailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 16,
  },
  detailKey: {
    fontSize: 14,
    color: GRAY[500],
  },
  detailValue: {
    fontSize: 14,
    fontWeight: "600",
    color: GRAY[200],
  },
  detailValueMono: {
    fontSize: 14,
    fontFamily: "monospace",
    color: GRAY[200],
  },
  infoBox: {
    marginTop: 20,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: GRAY[800],
    backgroundColor: GRAY[900],
    padding: 16,
  },
  infoBoxTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: "#ffffff",
  },
  infoBoxBody: {
    marginTop: 8,
    fontSize: 14,
    lineHeight: 22,
    color: GRAY[400],
  },
  primaryButton: {
    marginTop: 20,
    borderRadius: 8,
    backgroundColor: "#2563eb",
    paddingHorizontal: 16,
    paddingVertical: 12,
    alignItems: "center",
  },
  primaryButtonText: {
    fontSize: 14,
    fontWeight: "900",
    color: "#ffffff",
  },
  contactList: {
    marginTop: 16,
    gap: 8,
  },
  contactButton: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: GRAY[800],
    backgroundColor: GRAY[900],
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  contactButtonSelected: {
    borderColor: "#ea580c",
    backgroundColor: "rgba(67,20,7,0.3)",
  },
  contactName: {
    fontSize: 14,
    fontWeight: "600",
    color: "#ffffff",
  },
  contactUseCase: {
    marginTop: 4,
    fontSize: 12,
    color: GRAY[500],
  },
  emptyBox: {
    marginTop: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: GRAY[800],
    backgroundColor: GRAY[900],
    padding: 16,
  },
  emptyText: {
    fontSize: 14,
    color: GRAY[500],
  },
  threadHint: {
    marginTop: 4,
    fontSize: 14,
    color: GRAY[500],
  },
  threadList: {
    marginTop: 20,
    gap: 12,
  },
  threadMessage: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: GRAY[800],
    backgroundColor: GRAY[900],
    padding: 12,
  },
  threadBody: {
    fontSize: 14,
    lineHeight: 22,
    color: GRAY[200],
  },
  threadTime: {
    marginTop: 8,
    fontSize: 12,
    color: GRAY[500],
  },
});

// packages/wallet/src/components/bitnames/BitMessagesPreview.vue
<!-- packages/wallet/src/components/bitnames/BitMessagesPreview.vue -->

<script setup lang="ts">
import { computed, ref } from "vue";
import CoinNewsPreview from "./CoinNewsPreview.vue";

interface BitNamesContact {
  name: string;
  displayName: string;
  useCase: string;
  status: string;
  lastSeen: string;
  paymentHint: string;
}

interface BitNamesMessage {
  contact: string;
  side: "sent" | "received";
  time: string;
  body: string;
}

const props = defineProps<{
  contacts: BitNamesContact[];
  messages: BitNamesMessage[];
  selectedContactName: string;
}>();

const emit = defineEmits<{
  "update:selectedContactName": [value: string];
}>();

const selectedContact = computed(() => {
  return props.contacts.find((contact) => contact.name === props.selectedContactName);
});

const selectedConversation = computed(() => {
  return props.messages.filter((message) => message.contact === props.selectedContactName);
});

const composerOpenNonce = ref(0);

function selectContact(contactName: string) {
  emit("update:selectedContactName", contactName);
}

function openFeedComposer() {
  composerOpenNonce.value += 1;
}
</script>

<template>
  <div class="mt-6 space-y-6">
    <div class="rounded-2xl border border-gray-800 bg-gradient-to-br from-gray-950 via-gray-950 to-gray-900 p-6">
      <div class="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between">
        <div>
          <div class="flex flex-wrap items-center gap-2">
            <p class="text-xs uppercase tracking-widest text-ecash-500">
              BitNames identity
            </p>
            <span class="rounded-full border border-ecash-500/40 bg-ecash-950/60 px-2.5 py-1 text-xs font-black uppercase tracking-wide text-ecash-300">
              Live Coin News
            </span>
          </div>

          <h3 class="mt-3 text-3xl font-black text-white">BitMessages</h3>
          <p class="mt-3 max-w-3xl text-sm leading-6 text-gray-400">
            Broadcast signed posts, weekly news, and BitNames-linked messages
            across Signet from one wallet-native identity surface.
          </p>
        </div>

        <div class="grid grid-cols-3 gap-3 rounded-2xl border border-gray-800 bg-gray-950/70 p-3 text-center">
          <div class="px-3 py-2">
            <p class="text-lg font-black text-amber-400">—</p>
            <p class="text-[10px] uppercase tracking-wide text-gray-500">Messages</p>
          </div>
          <div class="border-x border-gray-800 px-3 py-2">
            <p class="text-lg font-black text-ecash-400">Live</p>
            <p class="text-[10px] uppercase tracking-wide text-gray-500">News</p>
          </div>
          <div class="px-3 py-2">
            <p class="text-lg font-black text-ecash-400">Signet</p>
            <p class="text-[10px] uppercase tracking-wide text-gray-500">Network</p>
          </div>
        </div>
      </div>
    </div>

    <div class="grid gap-6 xl:grid-cols-[minmax(0,1.25fr)_minmax(360px,0.75fr)]">
      <div>
        <CoinNewsPreview
          :show-hero="false"
          :composer-open-nonce="composerOpenNonce"
        />
      </div>

      <aside class="space-y-6">
        <section class="rounded-2xl border border-gray-800 bg-gray-950 p-5">
          <div class="flex items-start justify-between gap-3">
            <div>
              <p class="text-xs uppercase tracking-widest text-gray-500">
                Identity
              </p>
              <h3 class="mt-2 text-xl font-black text-white">
                {{ selectedContact?.name ?? "No live identity selected" }}
              </h3>
            </div>
            <span
              v-if="selectedContact"
              class="rounded-full bg-ecash-900 px-3 py-1 text-xs font-black text-ecash-300"
            >
              Resolved
            </span>
          </div>

          <dl class="mt-5 space-y-3 text-sm">
            <div class="flex justify-between gap-4">
              <dt class="text-gray-500">Default feed</dt>
              <dd class="font-semibold text-gray-200">Live indexed feed</dd>
            </div>
            <div class="flex justify-between gap-4">
              <dt class="text-gray-500">Message fee</dt>
              <dd class="font-mono text-ecash-300">Indexed live</dd>
            </div>
            <div class="flex justify-between gap-4">
              <dt class="text-gray-500">Contact</dt>
              <dd class="font-mono text-gray-200">
                {{ selectedContact?.name ?? "—" }}
              </dd>
            </div>
          </dl>
        </section>

        <section class="rounded-2xl border border-gray-800 bg-gray-950 p-5">
          <h3 class="text-xl font-black text-white">Broadcast News</h3>

          <div class="mt-5 rounded-xl border border-gray-800 bg-gray-900 p-4">
            <p class="text-sm font-semibold text-white">Local composer available</p>
            <p class="mt-2 text-sm leading-6 text-gray-400">
              Use the Coin News feed panel to build, sign, review, and broadcast
              a wallet-controlled OP_RETURN post.
            </p>
          </div>

          <button
            type="button"
            class="mt-5 w-full rounded-lg bg-blue-600 px-4 py-3 text-sm font-black text-white hover:bg-blue-500"
            @click="openFeedComposer"
          >
            Open Feed Composer
          </button>
        </section>

        <section class="rounded-2xl border border-gray-800 bg-gray-950 p-5">
          <h3 class="text-xl font-black text-white">Contacts</h3>

          <div v-if="contacts.length === 0" class="mt-4 rounded-xl border border-gray-800 bg-gray-900 p-4 text-sm text-gray-500">
            No live BitNames contacts are indexed yet.
          </div>

          <div v-else class="mt-4 space-y-2">
            <button
              v-for="contact in contacts"
              :key="contact.name"
              type="button"
              class="w-full rounded-lg border px-4 py-3 text-left transition-colors"
              :class="selectedContactName === contact.name ? 'border-ecash-600 bg-ecash-950/30' : 'border-gray-800 bg-gray-900 hover:border-gray-700'"
              @click="selectContact(contact.name)"
            >
              <p class="font-semibold text-white">{{ contact.name }}</p>
              <p class="mt-1 text-xs text-gray-500">{{ contact.useCase }}</p>
            </button>
          </div>
        </section>

        <section class="rounded-2xl border border-gray-800 bg-gray-950 p-5">
          <h3 class="text-xl font-black text-white">BitNames Thread</h3>
          <p class="mt-1 text-sm text-gray-500">
            {{ selectedContact?.paymentHint ?? "No live BitNames conversation selected." }}
          </p>

          <div v-if="selectedConversation.length === 0" class="mt-5 rounded-xl border border-gray-800 bg-gray-900 p-4 text-sm text-gray-500">
            No live BitNames messages are indexed yet.
          </div>

          <div v-else class="mt-5 space-y-3">
            <div
              v-for="message in selectedConversation"
              :key="`${message.contact}-${message.time}-${message.body}`"
              class="rounded-xl border border-gray-800 bg-gray-900 p-3"
            >
              <p class="text-sm leading-6 text-gray-200">{{ message.body }}</p>
              <p class="mt-2 text-xs text-gray-500">{{ message.time }}</p>
            </div>
          </div>
        </section>
      </aside>
    </div>
  </div>
</template>
